services:
  db:
    image: mongo:6
    container_name: todo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  api:
    build: ./backend
    container_name: todo_backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://db:27017/todolist 
      PORT: 5000
      JWT_SECRET: 0CZakfz7dsxtRhkEoqTrF0hI3AB2610aVD+iVSzhJzroiDWBpgRQHbFqk8d4faza
    depends_on:
      - db
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    networks:
      - app_network

  web:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:5000
    container_name: todo_frontend
    user: "node"
    ports:
      - "8080:8080"
    environment:
      VITE_API_URL: http://localhost:5000
    depends_on:
      - api
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    networks:
      - app_network

#  tests:
#    build: ./backend
#    container_name: todo_tests
#    command: npm test 
#    environment:
#      MONGO_URI: mongodb://db:27017/todolist_test
#    depends_on:
#      - api
#    networks:
#      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge