version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: todo_db
    environment:
      MYSQL_ROOT_PASSWORD: W4TCHD0G$
      MYSQL_DATABASE: todo_list
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  
    networks:
      - todo_network

  backend:
    build: ./backend
    container_name: todo_backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db 
      DB_USER: root
      DB_PASS: W4TCHD0G$
    depends_on:
      - db
    networks:
      - todo_network

  frontend:
    build: ./frontend
    container_name: todo_frontend
    ports:
      - "5173:5173" 
    environment:
      VITE_API_URL: http://localhost:3000 
    depends_on:
      - backend
    networks:
      - todo_network

  tests:
    build: ./backend 
    container_name: todo_tests
    command: yarn test
    environment:
      DB_HOST: db
    depends_on:
      - backend
    networks:
      - todo_network

volumes:
  mysql_data:

networks:
  todo_network:
    driver: bridge